# Shell variables
# Generated by 'wal'
wallpaper='/home/devm4n/Downloads/wal2.jpg'

# Special
background='#0C0E1B'
foreground='#dee2e1'
cursor='#dee2e1'

# Colors
color0='#0C0E1B'
color1='#B8B659'
color2='#71A19A'
color3='#15C8E1'
color4='#2DE3E9'
color5='#40DADC'
color6='#A1B0AB'
color7='#dee2e1'
color8='#9b9e9d'
color9='#B8B659'
color10='#71A19A'
color11='#15C8E1'
color12='#2DE3E9'
color13='#40DADC'
color14='#A1B0AB'
color15='#dee2e1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
